### PR TITLE
Implement a Stacked Scratch Area

### PR DESCRIPTION
**Pull request by jtenner**
This allows for messages to be stacked. Calling create_message() adds a message onto the stack, and any message modificatiosn modify the message on the top of the stack.

This is an experiment per a discussion I had with @bkolobara .

### CODE REVIEW

**Comment by tqwewe** [comment]
This is interesting, whats the main benefit of this, is it to be able to store multiple thingsi n the scratch area?

**Comment by withtypes** [comment]
I also played with similar ideas:

- you create a new message and receive a handle that you can use (write into it, drop it, send it once or multiple times)
- you receive a message and receive a handle and you can decide to read only a few bytes, to forward it, or drop it when you don't want to keep it in lunatic memory anymore

**Comment by bkolobara** [comment]
There could also be an opportunity for a bigger abstraction here. Instead of message handles, we could be creating general buffers in the vm. They could be sent as part of messages, but also be used for other stuff, like "read a tcp stream into a buffer, one process checks just a few bytes (path) and dispatches it to a handler".

**Comment by jtenner** [comment]
I don't know what the right decision is, but I want to revisit this further. It would involve refactoring the entire message api altogether.

**Pull request closed without merging**
